# Makefile for edm top level
TOP = ../..
include $(TOP)/configure/CONFIG
DIRS +=  util 
DIRS += lib 
DIRS += baselib 
DIRS += edmMain 
DIRS += pvlib 
DIRS += giflib 
DIRS += pnglib 
DIRS += pvFactory 
DIRS += choiceButton
DIRS += videowidget
DIRS += triumflib
include $(TOP)/configure/RULES_DIRS
